"""CM L4 bumped 3-tier empirical-network stress driver.

Runs the CM L4 self-RNG byte-equal check on the bumped 3-tier panel
(every network in `data/empirical_networks/networks/` with `n ≤ 30000`
per `_common/empirical_panel.py`; 161 fixtures, 50 seeds = 8050 cells
per algorithm) × {leiden-cpm:0.0001, leiden-mod:N/A} × 1log_10(n).
CM tracer chains VieCut + Leiden + WCC + log10 (per cm_audit.md row D =
WCC threshold, row A = TWO RNG streams).

Per (fixture, seed, algorithm): the input partition is generated by
running the **Leiden tracer** (canonical pipeline, /tmp/leiden_kernel_check)
with quality matching the CM base method:
  - --algorithm leiden-cpm  -> input partition = Leiden-CPM @ resolution
  - --algorithm leiden-mod  -> input partition = Leiden-Mod (no gamma)
The cpp CM tracer (/tmp/cm_kernel_check_swapped) then emits per-pop trace
JSON; self_rng_check.mjs runs the JS production walker (own VieCut + own
Leiden + own log10, no oracles) and bit-compares per-pop record under
matching MT19937 seed. PASS = 0 mismatches per cell.

Avoids seed=0 (igraph MT19937 quirk maps 0 -> 4357 per
`rng_mt19937.c:92-94`).

Usage:
    python stress_3tier.py [--tiers T1,T2,T3] [--seeds s1,...]
                            [--algorithm leiden-cpm|leiden-mod]
                            [--resolution 0.0001] [--workers N]
                            [--quick] [--timeout 1800]
"""
from __future__ import annotations

import argparse
import os
import subprocess
import sys
import time
from concurrent.futures import ProcessPoolExecutor, as_completed
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent / "_common"))
import driver as D  # noqa: E402
from empirical_panel import discover_panel, SEEDS_50  # noqa: E402

REPO = D.repo_root_from_here(HERE)
CM_TRACER = Path("/tmp/cm_kernel_check_swapped")
LEIDEN_TRACER = Path("/tmp/leiden_kernel_check")
SBM_TRACER = Path("/tmp/sbm_flat_kernel_check")
CHECK = HERE / "self_rng_check.mjs"

CRITERION = "1log_10(n)"


def make_input_partition_leiden(algorithm: str, resolution: float,
                                edge_path: Path, com_path: Path, seed: int,
                                timeout: int) -> tuple[bool, str]:
    """Generate the CM input partition by running the Leiden tracer on the
    full graph (canonical-shape libleidenalg via /tmp/leiden_kernel_check).
    Mirrors cm.cpp:17-20 GetCommunities bootstrap, but with argv seed (not
    the canonical hardcoded seed=0) so each (fixture,seed) cell exercises
    a distinct membership."""
    if algorithm == "leiden-cpm":
        quality = "cpm"; param = resolution
    elif algorithm == "leiden-mod":
        quality = "mod"; param = 1.0
    else:
        return False, f"leiden input not supported for algorithm: {algorithm}"
    try:
        rc = subprocess.run(
            [str(LEIDEN_TRACER), str(edge_path), str(com_path),
             quality, str(param), str(seed), "1"],
            capture_output=True, timeout=timeout,
        )
    except subprocess.TimeoutExpired:
        return False, "leiden tracer timeout"
    if rc.returncode != 0:
        tail = rc.stderr[-400:].decode("utf-8", "replace")
        return False, f"leiden rc={rc.returncode}: {tail}"
    return True, ""


def _synth_mod_K_partition(edge_path: Path, init_path: Path, seed: int) -> None:
    """Mod-K assignment over first-encounter node order (K = (seed%7)+2)."""
    nodes: list[str] = []
    seen: set[str] = set()
    with edge_path.open() as f:
        next(f)  # header
        for line in f:
            parts = line.strip().split(",")[:2]
            if len(parts) < 2:
                continue
            s, t = parts
            if s not in seen:
                seen.add(s); nodes.append(s)
            if t not in seen:
                seen.add(t); nodes.append(t)
    K = (seed % 7) + 2
    with init_path.open("w") as f:
        f.write("node_id,cluster_id\n")
        for i, nid in enumerate(nodes):
            f.write(f"{nid},{i % K}\n")


def make_input_partition_sbm_flat_pp(edge_path: Path, com_path: Path,
                                     seed: int, sweeps: int,
                                     timeout: int,
                                     scratch_dir: Path,
                                     tag: str) -> tuple[bool, str]:
    """Generate the CM input partition by running the SBM-Flat-PP tracer
    (mode=pp, single level) on the full graph. Init partition is mod-K
    membership over first-encounter node order (K = (seed%7)+2). PP =
    Zhang+Peixoto 2020 planted-partition likelihood; the SBM mcmc_sweep
    refines this initial partition over `sweeps` Metropolis-Hastings
    iterations. Final block assignment becomes CM's input com.csv.
    Per cd_tracer_session_handoff: SBM is NOT a canonical CM base method;
    its use here is as an INPUT-partition source only. CM's base method
    (leiden-mod / leiden-cpm) remains canonical-aligned per cm.cpp."""
    init_path = scratch_dir / f"{tag}_sbm_init.csv"
    trace_path = scratch_dir / f"{tag}_sbm_trace.json"
    err_path = scratch_dir / f"{tag}_sbm_trace.err"
    try:
        _synth_mod_K_partition(edge_path, init_path, seed)
    except Exception as e:
        return False, f"sbm init synth: {e}"
    try:
        rc = subprocess.run(
            [str(SBM_TRACER), "--mode=pp", f"--edge={edge_path}",
             f"--init={init_path}", f"--seed={seed}", f"--sweeps={sweeps}"],
            capture_output=True, timeout=timeout,
        )
    except subprocess.TimeoutExpired:
        return False, "sbm tracer timeout"
    if rc.returncode != 0:
        tail = rc.stderr[-400:].decode("utf-8", "replace")
        return False, f"sbm rc={rc.returncode}: {tail}"
    trace_path.write_bytes(rc.stdout)
    err_path.write_bytes(rc.stderr)
    # Parse final_membership + renum_to_orig from SBM JSON, write com.csv.
    try:
        import json as _json
        with trace_path.open() as f:
            d = _json.load(f)
        mem = d["final_membership"]
        renum = d["renum_to_orig"]
        with com_path.open("w") as f:
            f.write("node_id,cluster_id\n")
            for i, orig in enumerate(renum):
                f.write(f"{orig},{mem[i]}\n")
    except Exception as e:
        return False, f"sbm com extract: {e}"
    # Cleanup SBM trace + init (we only need com.csv).
    for p in (init_path, trace_path, err_path):
        try: p.unlink()
        except OSError: pass
    return True, ""


def make_input_partition(input_source: str, algorithm: str,
                         resolution: float, edge_path: Path, com_path: Path,
                         seed: int, sbm_sweeps: int, timeout: int,
                         scratch_dir: Path, tag: str) -> tuple[bool, str]:
    """Dispatch by input source. `algorithm` and `resolution` apply only
    to leiden input sources; `sbm_sweeps` applies to sbm-flat-pp."""
    if input_source == "leiden":
        return make_input_partition_leiden(algorithm, resolution, edge_path,
                                           com_path, seed, timeout)
    if input_source == "sbm-flat-pp":
        return make_input_partition_sbm_flat_pp(edge_path, com_path, seed,
                                                sbm_sweeps, timeout,
                                                scratch_dir, tag)
    return False, f"unsupported input source: {input_source}"


def parse_div(log: str) -> tuple[int, int, int, str]:
    """Extract (cpp_pops, js_pops, survivors, last_line) from check log."""
    cpp_pops = 0
    js_pops = 0
    survivors = 0
    for line in log.splitlines():
        if "cpp pops=" in line:
            for tok in line.split():
                if tok.startswith("pops="):
                    try: cpp_pops = max(cpp_pops, int(tok.split("=", 1)[1]))
                    except ValueError: pass
        if "js pops=" in line:
            for tok in line.split():
                if tok.startswith("pops="):
                    try: js_pops = max(js_pops, int(tok.split("=", 1)[1]))
                    except ValueError: pass
        if "clusters w/ lineage" in line:
            try:
                survivors = int(line.strip().split()[0])
            except (ValueError, IndexError):
                pass
    last = log.splitlines()[-1] if log.splitlines() else "(no output)"
    return cpp_pops, js_pops, survivors, last


def run_cell(name: str, edge: str, seed: int, input_source: str,
             algorithm: str, resolution: float, sbm_sweeps: int,
             timeout: int, scratch: str) -> tuple[str, int, bool, int, int, int, str]:
    """One (fixture, seed) cell. Returns
    (name, seed, ok, cpp_pops, js_pops, survivors, last_line)."""
    edge_path = Path(edge)
    scratch_dir = Path(scratch)
    scratch_dir.mkdir(parents=True, exist_ok=True)
    tag = f"{name}_{input_source}_{algorithm}_s{seed}"
    com = scratch_dir / f"{tag}.com"
    out = scratch_dir / f"{tag}.out"
    trace = scratch_dir / f"{tag}.json"
    err = scratch_dir / f"{tag}.err"

    # Step 1: produce input partition (leiden | sbm-flat-pp).
    ok, msg = make_input_partition(input_source, algorithm, resolution,
                                   edge_path, com, seed, sbm_sweeps,
                                   timeout, scratch_dir, tag)
    if not ok:
        return name, seed, False, 0, 0, 0, f"input_partition: {msg}"

    # Step 2: run cpp CM tracer (TRACER_MODE swapped build).
    try:
        rc = subprocess.run(
            [str(CM_TRACER), str(edge_path), str(com), str(out),
             CRITERION, str(resolution), str(seed), algorithm],
            capture_output=True, timeout=timeout,
        )
    except subprocess.TimeoutExpired:
        return name, seed, False, 0, 0, 0, "cm tracer timeout"
    if rc.returncode != 0:
        tail = rc.stderr[-400:].decode("utf-8", "replace")
        return name, seed, False, 0, 0, 0, f"cm tracer rc={rc.returncode}: {tail}"
    trace.write_bytes(rc.stdout)
    err.write_bytes(rc.stderr)

    # Step 3: run JS self-RNG check.
    try:
        rc = subprocess.run(
            ["node", str(CHECK), str(trace), str(edge_path), str(com),
             CRITERION, str(resolution), str(seed), algorithm],
            capture_output=True, text=True, timeout=timeout,
        )
    except subprocess.TimeoutExpired:
        return name, seed, False, 0, 0, 0, "js check timeout"

    log = (rc.stdout + rc.stderr).strip()
    cpp_pops, js_pops, survivors, last = parse_div(log)
    ok = rc.returncode == 0
    if ok:
        for f in (com, out, trace, err):
            try: f.unlink()
            except OSError: pass
    return name, seed, ok, cpp_pops, js_pops, survivors, last


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--tiers", default="T1,T2,T3")
    ap.add_argument("--seeds", default=",".join(str(s) for s in SEEDS_50))
    ap.add_argument("--input-source", default="leiden",
                    choices=("leiden", "sbm-flat-pp"),
                    help="CM input partition source (default leiden)")
    ap.add_argument("--algorithm", default="leiden-mod",
                    help="CM base method: leiden-cpm | leiden-mod (default leiden-mod). "
                         "Used both for leiden input-source quality choice AND CM base method.")
    ap.add_argument("--resolution", type=float, default=0.0001,
                    help="resolution for leiden-cpm; ignored for leiden-mod")
    ap.add_argument("--sbm-sweeps", type=int, default=10,
                    help="Number of mcmc_sweep iterations for sbm-flat-pp input (default 10)")
    ap.add_argument("--workers", type=int, default=os.cpu_count() or 4)
    ap.add_argument("--quick", action="store_true",
                    help="3 seeds × 1 fixture per tier (smoke).")
    ap.add_argument("--timeout", type=int, default=1800,
                    help="per-cell timeout in seconds (T3 cells: bump to >=1800)")
    ap.add_argument("--scratch", default="/tmp/cm_stress_3tier")
    ap.add_argument("--max-per-tier", type=int, default=0,
                    help="cap fixture count per tier (0 = unlimited)")
    args = ap.parse_args()

    tiers = args.tiers.split(",")
    panel = discover_panel(REPO)
    if args.quick:
        seeds = SEEDS_50[:3]
        per_tier_cap: int | None = 1
    else:
        seeds = [int(s) for s in args.seeds.split(",")]
        per_tier_cap = args.max_per_tier or None

    if not CM_TRACER.is_file():
        sys.exit(f"CM tracer binary missing: {CM_TRACER}\n"
                 f"build via: bash {HERE}/instrumented/build.sh")
    if args.input_source == "leiden" and not LEIDEN_TRACER.is_file():
        sys.exit(f"Leiden tracer binary missing: {LEIDEN_TRACER}\n"
                 f"build via: bash {REPO}/tools/viz_check/leiden/instrumented/build.sh")
    if args.input_source == "sbm-flat-pp" and not SBM_TRACER.is_file():
        sys.exit(f"SBM tracer binary missing: {SBM_TRACER}\n"
                 f"build via: bash {REPO}/tools/viz_check/sbm/instrumented/build.sh")

    tier_cells: dict[str, list[tuple[str, str, int]]] = {}
    for tier in tiers:
        if tier not in panel:
            sys.exit(f"unknown tier: {tier}")
        fixtures = panel[tier]
        if per_tier_cap is not None:
            fixtures = fixtures[:per_tier_cap]
        cells: list[tuple[str, str, int]] = []
        for fx in fixtures:
            for seed in seeds:
                cells.append((fx["subnet"], fx["edge"], seed))
        tier_cells[tier] = cells

    total_cells = sum(len(c) for c in tier_cells.values())
    print(f"CM L4 bumped 3-tier stress: input_source={args.input_source} "
          f"algorithm={args.algorithm} resolution={args.resolution} "
          f"tiers={','.join(tiers)} seeds={len(seeds)} "
          f"workers={args.workers} timeout={args.timeout}s "
          f"total_cells={total_cells}")
    print(f"  criterion={CRITERION} sbm_sweeps={args.sbm_sweeps}")
    for tier in tiers:
        print(f"  {tier}: {len(panel[tier])} fixtures")
    print()
    sys.stdout.flush()

    grand_pass = 0
    grand_fail = 0
    grand_records = 0
    failed_cells: list[tuple[str, str, int, str]] = []
    t0 = time.time()

    for tier in tiers:
        cells = tier_cells[tier]
        if not cells:
            continue
        print(f"=== {tier} ({len(cells)} cells) ===")
        sys.stdout.flush()
        tier_pass = tier_fail = tier_records = 0
        results: list[tuple] = []
        with ProcessPoolExecutor(max_workers=args.workers) as ex:
            futures = [
                ex.submit(run_cell, *c, args.input_source, args.algorithm,
                          args.resolution, args.sbm_sweeps,
                          args.timeout, args.scratch)
                for c in cells
            ]
            for fut in as_completed(futures):
                results.append(fut.result())
        results.sort(key=lambda r: (r[0], r[1]))
        for name, seed, ok, cpp_pops, js_pops, survivors, tail in results:
            tier_records += cpp_pops + survivors
            if ok:
                tier_pass += 1
            else:
                tier_fail += 1
                failed_cells.append((tier, name, seed, tail))
                print(f"  FAIL {name} seed={seed} cpp_pops={cpp_pops} "
                      f"js_pops={js_pops}: {tail}")
                sys.stdout.flush()
        grand_pass += tier_pass
        grand_fail += tier_fail
        grand_records += tier_records
        print(f"  {tier}: PASS={tier_pass} FAIL={tier_fail} "
              f"records={tier_records:,}")
        sys.stdout.flush()

    elapsed = time.time() - t0
    print()
    print("=== SUMMARY ===")
    print(f"Cells: PASS={grand_pass} FAIL={grand_fail} "
          f"(total={grand_pass + grand_fail})")
    print(f"Cumulative records (cpp_pops + survivors): {grand_records:,}")
    print(f"Wall: {elapsed:.1f}s")
    if failed_cells:
        print()
        print("Failed cells:")
        for tier, name, seed, tail in failed_cells[:50]:
            print(f"  {tier}/{name} seed={seed}: {tail}")
    if grand_fail == 0 and grand_pass > 0:
        print("OVERALL: PASS")
    elif grand_pass == 0:
        print("OVERALL: NO CELLS RUN")
    else:
        print("OVERALL: FAIL")
    return 0 if grand_fail == 0 and grand_pass > 0 else 1


if __name__ == "__main__":
    sys.exit(main())
